set_property IOSTANDARD LVCMOS33 [get_ports and_gate]
set_property IOSTANDARD LVCMOS33 [get_ports a]
set_property IOSTANDARD LVCMOS33 [get_ports b]
set_property IOSTANDARD LVCMOS33 [get_ports not_gate]
set_property IOSTANDARD LVCMOS33 [get_ports nor_gate]
set_property IOSTANDARD LVCMOS33 [get_ports nand_gate]
set_property IOSTANDARD LVCMOS33 [get_ports or_gate]
set_property IOSTANDARD LVCMOS33 [get_ports xor_gate]
set_property PACKAGE_PIN P1 [get_ports a]
set_property PACKAGE_PIN P2 [get_ports b]
set_property PACKAGE_PIN E2 [get_ports and_gate]
set_property PACKAGE_PIN E3 [get_ports nand_gate]
set_property PACKAGE_PIN E5 [get_ports nor_gate]
set_property PACKAGE_PIN E6 [get_ports not_gate]
set_property PACKAGE_PIN C3 [get_ports or_gate]
set_property PACKAGE_PIN B2 [get_ports xor_gate]
set_property CFGBVS VCCO [current_design]
set_property CONFIG_VOLTAGE 3.3 [current_design]

